/**
 * На промоигле
 * Задача для Alfa Battle от X5 Retail Group
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.katsman.alfabattle.task1.dto

import java.math.BigDecimal

/**
 * Результат расчета корзины
 * @param discount Полная сумма скидки
 * @param positions Результат расчета цен по позициям
 * @param total Полная сумма чека с применением скидок
 */
data class FinalPriceReceipt(
    /* Полная сумма скидки */
    val discount: BigDecimal,
    /* Результат расчета цен по позициям */
    val positions: List<FinalPricePosition>,
    /* Полная сумма чека с применением скидок */
    val total: BigDecimal
)
