/**
 * На промоигле
 * Задача для Alfa Battle от X5 Retail Group
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.katsman.alfabattle.task1.dto

/**
 * Позиция товара в корзине
 * @param itemId ID товара
 * @param quantity Количество товара в позиции
 */
data class ItemPosition(
    /* ID товара */
    val itemId: String,
    /* Количество товара в позиции */
    val quantity: Int
)
