/**
 * На промоигле
 * Задача для Alfa Battle от X5 Retail Group
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.katsman.alfabattle.task1.dto

/**
 * Параметры скидки при предъявлении пенсионного удостоверения или социальной карты
 * @param discount Коэффициент скидки (сидка = цена * discount)
 * @param shopId Номер магазина, -1 для акции сети
 */
data class LoyaltyCardRule(
    /* Коэффициент скидки (сидка = цена * discount) */
    val discount: Double,
    /* Номер магазина, -1 для акции сети */
    val shopId: Int
)
